// Drinking Jenga Tasks Database
// Task Types: standard | timer | countdown | vote | spinner
// Placeholders: {player} = current player, {other} = random other player, {all} = everyone

const TASKS = {
  calm: [
    // Basic drinking tasks (20)
    { text: "Take 2 sips of water", type: "standard" },
    { text: "Take 3 sips of water", type: "standard" },
    { text: "Take 4 sips of water", type: "standard" },
    { text: "Take a big gulp of water", type: "standard" },
    { text: "Take 2 small sips", type: "standard" },
    { text: "Hydrate! Take 5 sips", type: "standard" },
    { text: "Sip your water slowly for 10 seconds", type: "countdown", config: { duration: 10, task: "Sip slowly!" } },
    { text: "Take a refreshing drink", type: "standard" },
    { text: "Water break! 3 sips for you", type: "standard" },
    { text: "Quench your thirst with 4 sips", type: "standard" },
    { text: "Take 2 sips and say 'ahh'", type: "standard" },
    { text: "Drink until you need to breathe", type: "standard" },
    { text: "Take exactly 6 sips", type: "standard" },
    { text: "One big sip for {player}", type: "standard" },
    { text: "Hydration station! Take 3 sips", type: "standard" },
    { text: "Water time! 2 sips minimum", type: "standard" },
    { text: "Take a victory sip", type: "standard" },
    { text: "Celebrate with 3 sips of water", type: "standard" },
    { text: "Cooling down? Take 4 sips", type: "standard" },
    { text: "Refreshment break: 5 sips", type: "standard" },

    // Social drinking tasks (25)
    { text: "Give a toast to {other} and both drink 2 sips", type: "standard" },
    { text: "Cheers with the person to your left, both drink", type: "standard" },
    { text: "Cheers with the person to your right, both drink", type: "standard" },
    { text: "Pick someone to drink 3 sips with you", type: "standard" },
    { text: "{all} take 1 sip together", type: "standard" },
    { text: "You and {other} both take 2 sips", type: "standard" },
    { text: "High-five {other}, then both drink", type: "standard" },
    { text: "Make eye contact with {other} while you both drink", type: "standard" },
    { text: "Toast to good health, {all} drink 1 sip", type: "standard" },
    { text: "Waterfall! {all} drink until {player} stops", type: "standard" },
    { text: "Pick 2 people to drink with you", type: "standard" },
    { text: "The person across from you drinks with you", type: "standard" },
    { text: "Youngest player drinks with you", type: "standard" },
    { text: "Oldest player drinks with you", type: "standard" },
    { text: "Person who went before you takes 2 sips", type: "standard" },
    { text: "Person who goes next takes 2 sips", type: "standard" },
    { text: "Everyone wearing the same color as you drinks", type: "standard" },
    { text: "{all} with glasses drink 2 sips", type: "standard" },
    { text: "{all} with long hair drink 2 sips", type: "standard" },
    { text: "{all} with short hair drink 2 sips", type: "standard" },
    { text: "Anyone born in the same month as you drinks", type: "standard" },
    { text: "Toast to the host, {all} drink", type: "standard" },
    { text: "Compliment {other} and both drink", type: "standard" },
    { text: "Tell {other} something nice, both drink 2 sips", type: "standard" },
    { text: "Link arms with {other} and drink together", type: "standard" },

    // Simple timed actions (15)
    { text: "Do a thumbs up and take 2 sips", type: "standard" },
    { text: "Wink at {other} then drink", type: "standard" },
    { text: "Blow a kiss to {all} then drink 2 sips", type: "standard" },
    { text: "Wave hello to everyone, take 3 sips", type: "standard" },
    { text: "Pat yourself on the back, drink 2 sips", type: "standard" },
    { text: "Give yourself a round of applause, drink", type: "standard" },
    { text: "Stretch your arms up, then drink 3 sips", type: "standard" },
    { text: "Touch your toes, then drink 2 sips", type: "standard" },
    { text: "Spin in your seat once, drink 2 sips", type: "standard" },
    { text: "Stand up, sit down, drink 3 sips", type: "standard" },
    { text: "Clap 5 times, then drink", type: "standard" },
    { text: "Snap your fingers 3 times, drink 2 sips", type: "standard" },
    { text: "Take a deep breath, then drink 4 sips", type: "standard" },
    { text: "Yawn dramatically, then hydrate with 3 sips", type: "standard" },
    { text: "Crack your knuckles, drink 2 sips", type: "standard" },

    // More simple actions (10)
    { text: "Roll your shoulders, drink 2 sips", type: "standard" },
    { text: "Nod your head 5 times, drink", type: "standard" },
    { text: "Shake your head no 5 times, drink", type: "standard" },
    { text: "Rub your belly, drink 3 sips", type: "standard" },
    { text: "Pat your head, drink 2 sips", type: "standard" },
    { text: "Touch your nose, drink 2 sips", type: "standard" },
    { text: "Pull your ear, drink 2 sips", type: "standard" },
    { text: "Wiggle your eyebrows, drink", type: "standard" },
    { text: "Stick out your tongue, drink 2 sips", type: "standard" },
    { text: "Cross your eyes briefly, drink 3 sips", type: "standard" },

    // Question/truth tasks (20)
    { text: "Share your favorite color, then drink 2 sips", type: "standard" },
    { text: "Tell {all} your favorite food, drink", type: "standard" },
    { text: "Share your zodiac sign, drink 2 sips", type: "standard" },
    { text: "Tell {all} your favorite movie, drink", type: "standard" },
    { text: "Share your favorite song, drink 2 sips", type: "standard" },
    { text: "Tell {all} your favorite animal, drink", type: "standard" },
    { text: "Share your favorite season, drink", type: "standard" },
    { text: "Tell {all} your favorite drink, drink 3 sips", type: "standard" },
    { text: "Share your favorite holiday, drink 2 sips", type: "standard" },
    { text: "Tell {all} your favorite sport, drink", type: "standard" },
    { text: "Share your favorite candy, drink 2 sips", type: "standard" },
    { text: "Tell {all} your middle name, drink", type: "standard" },
    { text: "Share your birth month, drink 2 sips", type: "standard" },
    { text: "Tell {all} your favorite pizza topping, drink", type: "standard" },
    { text: "Share your favorite ice cream flavor, drink", type: "standard" },
    { text: "Tell {all} your favorite superhero, drink 2 sips", type: "standard" },
    { text: "Share your least favorite vegetable, drink", type: "standard" },
    { text: "Tell {all} your favorite board game, drink", type: "standard" },
    { text: "Share your dream vacation spot, drink 2 sips", type: "standard" },
    { text: "Tell {all} your favorite childhood show, drink", type: "standard" },

    // Thumb/Question Master variations (15)
    { text: "You're the Thumb Master until someone else gets this card", type: "standard" },
    { text: "You're the Question Master until your next turn", type: "standard" },
    { text: "Point at {other}, they drink 2 sips", type: "standard" },
    { text: "Point at yourself, drink 3 sips", type: "standard" },
    { text: "Point at the ceiling, last person to look drinks", type: "timer", config: { duration: "3", showTime: false, sound: "buzzer", resultText: "Last one to look up drinks 3 sips!" } },
    { text: "Put your thumb on the table, last to notice drinks", type: "timer", config: { duration: "5", showTime: false, sound: "buzzer", resultText: "Last one with thumb down drinks 3 sips!" } },
    { text: "Touch your nose, last person to do it drinks 2 sips", type: "timer", config: { duration: "3", showTime: false, sound: "buzzer", resultText: "Slowest nose-toucher drinks 2 sips!" } },
    { text: "Raise your hand, last to raise theirs drinks", type: "timer", config: { duration: "3", showTime: false, sound: "buzzer", resultText: "Last hand up drinks 3 sips!" } },
    { text: "Put your hand on your head, last to follow drinks", type: "timer", config: { duration: "3", showTime: false, sound: "buzzer", resultText: "Slowpoke drinks 3 sips!" } },
    { text: "Cross your arms, last to follow drinks 2 sips", type: "timer", config: { duration: "3", showTime: false, sound: "buzzer", resultText: "Last one drinks 2 sips!" } },
    { text: "Close your eyes, last to close drinks", type: "timer", config: { duration: "3", showTime: false, sound: "buzzer", resultText: "Last eyes closed drinks 3 sips!" } },
    { text: "Cover your ears, last to follow drinks", type: "timer", config: { duration: "3", showTime: false, sound: "buzzer", resultText: "Slowest person drinks 3 sips!" } },
    { text: "Put your hands up, last one drinks 3 sips", type: "timer", config: { duration: "3", showTime: false, sound: "buzzer", resultText: "Hands up! Last one drinks 3!" } },
    { text: "Make a peace sign, last to follow drinks", type: "timer", config: { duration: "3", showTime: false, sound: "buzzer", resultText: "No peace for the slowest - drink 3!" } },
    { text: "Put your finger on your lips, last to shush drinks", type: "timer", config: { duration: "3", showTime: false, sound: "buzzer", resultText: "Shhh! Last one drinks 3 sips!" } },

    // Safe/pass cards (10)
    { text: "Safe! No drinking for you this turn", type: "standard" },
    { text: "Lucky block! Skip this turn's drink", type: "standard" },
    { text: "Free pass! Relax this round", type: "standard" },
    { text: "Bonus: Give your sips to {other}", type: "standard" },
    { text: "Transfer: {other} drinks 3 sips instead of you", type: "standard" },
    { text: "Shield: You're protected, {other} drinks for you", type: "standard" },
    { text: "Redirect: Point at someone, they drink 2 sips", type: "standard" },
    { text: "Lucky you! Pick someone else to drink 4 sips", type: "standard" },
    { text: "Golden block! You're safe, choose who drinks", type: "standard" },
    { text: "Escape card! Assign 5 sips to anyone", type: "standard" },

    // Creative tasks - Calm
    { text: "Toast! Make a heartfelt toast to the group, then {all} drink together", type: "standard" },
    { text: "Embryo! Youngest player in the group must drink 3 sips", type: "standard" },
    { text: "Old-Timer! Oldest player in the group must drink 3 sips", type: "standard" },
    { text: "Nose Goes! Last one to touch their nose drinks 3 sips!", type: "timer", config: { duration: "3", showTime: false, sound: "buzzer", resultText: "Last nose touched drinks 3 sips!" } },
    { text: "Marco! Yell 'MARCO!' - first to respond 'POLO' hands out 3 drinks!", type: "timer", config: { duration: "5", showTime: false, sound: "buzzer", resultText: "First POLO wins! They hand out 3 drinks!" } },
    { text: "Déjà Vu! The player before you must go again and draw another piece!", type: "standard" },
    { text: "Music Man! You're now in charge of the music for the rest of the game", type: "standard" },
    { text: "Thumb Master! Place your thumb on table edge anytime - last to notice drinks!", type: "standard" },
    { text: "Question Master! Anyone who answers your questions must drink until next turn", type: "standard" }
  ],

  mild: [
    // Drinking challenges (25)
    { text: "Drink for every letter in your first name", type: "standard" },
    { text: "Drink for every vowel in your name", type: "standard" },
    { text: "Drink your age divided by 5 (round up)", type: "standard" },
    { text: "Drink for how many siblings you have, minimum 2", type: "standard" },
    { text: "Drink for every pet you've ever owned, max 10", type: "standard" },
    { text: "Drink the number you're thinking of (1-5)", type: "standard" },
    { text: "Roll an imaginary die, drink that many sips", type: "standard" },
    { text: "Pick a number 1-6, drink that many", type: "standard" },
    { text: "Drink for every person in the room wearing blue", type: "standard" },
    { text: "Drink for every phone visible on the table", type: "standard" },
    { text: "Chug for 5 seconds", type: "countdown", config: { duration: 5, task: "CHUG! CHUG! CHUG!" } },
    { text: "Take 8 consecutive sips", type: "standard" },
    { text: "Drink half your current glass", type: "standard" },
    { text: "Finish what's in your cup and refill", type: "standard" },
    { text: "Take the biggest sip you can manage", type: "standard" },
    { text: "Drink for 10 seconds straight", type: "countdown", config: { duration: 10, task: "Keep drinking!" } },
    { text: "Take 7 sips without stopping", type: "standard" },
    { text: "Power drink: 6 quick sips", type: "standard" },
    { text: "Mega hydration: 10 sips", type: "standard" },
    { text: "Double down: drink twice your last amount", type: "standard" },
    { text: "Drink for every ring/bracelet you're wearing", type: "standard" },
    { text: "Drink for every button on your shirt", type: "standard" },
    { text: "Drink for the day of the month you were born (max 10)", type: "standard" },
    { text: "Drink for every social media app on your phone (max 8)", type: "standard" },
    { text: "Drink for every person taller than you in the room", type: "standard" },

    // Physical challenges with countdowns (25)
    { text: "Do 10 pushups or drink 5 sips", type: "countdown", config: { duration: 30, task: "10 pushups - GO!" } },
    { text: "Do 15 jumping jacks or drink 6 sips", type: "countdown", config: { duration: 20, task: "15 jumping jacks!" } },
    { text: "Do 20 squats or drink 8 sips", type: "countdown", config: { duration: 30, task: "20 squats - hustle!" } },
    { text: "Hold a plank for 20 seconds or drink 5 sips", type: "countdown", config: { duration: 20, task: "PLANK! Hold it!" } },
    { text: "Do 10 sit-ups or drink 4 sips", type: "countdown", config: { duration: 25, task: "10 sit-ups!" } },
    { text: "Touch your toes for 15 seconds or drink", type: "countdown", config: { duration: 15, task: "Touch those toes!" } },
    { text: "Do 5 burpees or drink 10 sips", type: "countdown", config: { duration: 30, task: "5 burpees - let's go!" } },
    { text: "Wall sit for 30 seconds or drink 7 sips", type: "countdown", config: { duration: 30, task: "WALL SIT! Don't give up!" } },
    { text: "Run in place for 20 seconds, then drink 3 sips", type: "countdown", config: { duration: 20, task: "Run run run!" } },
    { text: "Do 10 high knees, then drink 2 sips", type: "countdown", config: { duration: 15, task: "High knees!" } },
    { text: "Balance on one foot for 15 seconds or drink 4 sips", type: "countdown", config: { duration: 15, task: "Balance! Don't fall!" } },
    { text: "Do 5 lunges each leg or drink 5 sips", type: "countdown", config: { duration: 25, task: "Lunge it out!" } },
    { text: "Arm circles for 20 seconds, drink 2 sips", type: "countdown", config: { duration: 20, task: "Circle those arms!" } },
    { text: "Do 10 calf raises, drink 2 sips", type: "countdown", config: { duration: 15, task: "Calf raises!" } },
    { text: "Hold your arms out for 30 seconds or drink", type: "countdown", config: { duration: 30, task: "Arms out! T-pose!" } },
    { text: "Do 5 pushups, {other} counts, drink 3 sips after", type: "standard" },
    { text: "Hop on one foot 10 times, drink 2 sips", type: "standard" },
    { text: "Do a wall push for 15 seconds, drink after", type: "countdown", config: { duration: 15, task: "Push that wall!" } },
    { text: "Stretch and hold for 20 seconds, then drink", type: "countdown", config: { duration: 20, task: "Stretch it out!" } },
    { text: "March in place for 15 seconds, drink 3 sips", type: "countdown", config: { duration: 15, task: "March! Left, right!" } },
    { text: "Do 10 arm pumps, drink 2 sips", type: "standard" },
    { text: "Shadow box for 10 seconds, drink 3 sips", type: "countdown", config: { duration: 10, task: "Float like a butterfly!" } },
    { text: "Dance in place for 10 seconds, drink 2 sips", type: "countdown", config: { duration: 10, task: "Dance! Show your moves!" } },
    { text: "Shake your whole body for 5 seconds, drink", type: "countdown", config: { duration: 5, task: "Shake it off!" } },
    { text: "Do your best stretch, hold 10 seconds, drink 2 sips", type: "countdown", config: { duration: 10, task: "Stretch and hold!" } },

    // Category/word games with timers (20)
    { text: "Name 5 types of fruit in 10 seconds or drink 5 sips", type: "countdown", config: { duration: 10, task: "Name 5 fruits!" } },
    { text: "Name 5 car brands in 10 seconds or drink 5 sips", type: "countdown", config: { duration: 10, task: "Name 5 car brands!" } },
    { text: "Name 5 countries in 10 seconds or drink 5 sips", type: "countdown", config: { duration: 10, task: "Name 5 countries!" } },
    { text: "Name 5 dog breeds in 10 seconds or drink 5 sips", type: "countdown", config: { duration: 10, task: "Name 5 dog breeds!" } },
    { text: "Name 5 colors in 5 seconds or drink 3 sips", type: "countdown", config: { duration: 5, task: "Name 5 colors!" } },
    { text: "Name 5 pizza toppings in 8 seconds or drink 4 sips", type: "countdown", config: { duration: 8, task: "Name 5 pizza toppings!" } },
    { text: "Name 5 ice cream flavors in 8 seconds or drink 4 sips", type: "countdown", config: { duration: 8, task: "Name 5 ice cream flavors!" } },
    { text: "Name 5 sports in 8 seconds or drink 4 sips", type: "countdown", config: { duration: 8, task: "Name 5 sports!" } },
    { text: "Name 5 movies in 10 seconds or drink 5 sips", type: "countdown", config: { duration: 10, task: "Name 5 movies!" } },
    { text: "Name 5 songs in 10 seconds or drink 5 sips", type: "countdown", config: { duration: 10, task: "Name 5 songs!" } },
    { text: "Name 5 celebrities in 10 seconds or drink 5 sips", type: "countdown", config: { duration: 10, task: "Name 5 celebrities!" } },
    { text: "Name 5 US states in 8 seconds or drink 4 sips", type: "countdown", config: { duration: 8, task: "Name 5 US states!" } },
    { text: "Name 5 Disney movies in 10 seconds or drink 5 sips", type: "countdown", config: { duration: 10, task: "Name 5 Disney movies!" } },
    { text: "Rhyme time: Say a word, {all} must rhyme, first to fail drinks 5", type: "standard" },
    { text: "Word association with {other}, loser drinks 5 sips", type: "standard" },
    { text: "Spell 'necessary' in 5 seconds or drink 5 sips", type: "countdown", config: { duration: 5, task: "Spell 'necessary'!" } },
    { text: "Spell 'rhythm' in 5 seconds or drink 4 sips", type: "countdown", config: { duration: 5, task: "Spell 'rhythm'!" } },
    { text: "Name 3 things that start with 'S' in 5 seconds or drink", type: "countdown", config: { duration: 5, task: "3 things starting with S!" } },
    { text: "Count backwards from 20 in 10 seconds or drink 4 sips", type: "countdown", config: { duration: 10, task: "20, 19, 18... GO!" } },
    { text: "Recite the alphabet backwards, A-L, in 10 seconds or drink 6 sips", type: "countdown", config: { duration: 10, task: "L, K, J, I... GO!" } },

    // Social challenges (20)
    { text: "Swap seats with {other}, both drink 3 sips", type: "standard" },
    { text: "Switch drinks with {other} for this round", type: "standard" },
    { text: "Hold hands with {other} until your next turn or both drink 5", type: "standard" },
    { text: "Compliment everyone at the table, drink after", type: "standard" },
    { text: "Roast yourself mildly, then drink 4 sips", type: "standard" },
    { text: "Tell {all} your most embarrassing school moment, drink 3 sips", type: "standard" },
    { text: "Share your worst date story, drink 4 sips", type: "standard" },
    { text: "Admit your guilty pleasure, drink 3 sips", type: "standard" },
    { text: "Share your worst haircut story, drink 2 sips", type: "standard" },
    { text: "Tell {all} about a time you got in trouble, drink 3 sips", type: "standard" },
    { text: "Share your most awkward moment this year, drink 4 sips", type: "standard" },
    { text: "Describe your first crush without names, drink 3 sips", type: "standard" },
    { text: "Tell {all} your weirdest habit, drink 2 sips", type: "standard" },
    { text: "Share a secret talent, demonstrate it, drink 3 sips", type: "standard" },
    { text: "Tell {all} your biggest fear, drink 2 sips", type: "standard" },
    { text: "Share your dream job as a kid, drink 2 sips", type: "standard" },
    { text: "Tell {all} your most useless skill, drink 3 sips", type: "standard" },
    { text: "Share something {all} don't know about you, drink 4 sips", type: "standard" },
    { text: "Tell {all} your go-to karaoke song, drink 2 sips", type: "standard" },
    { text: "Share your worst cooking disaster, drink 3 sips", type: "standard" },

    // Accent/voice challenges (15)
    { text: "Speak in a British accent until your next turn", type: "standard" },
    { text: "Talk like a robot until your next turn", type: "standard" },
    { text: "Whisper everything until your next turn", type: "standard" },
    { text: "Speak in a Southern accent until your next turn", type: "standard" },
    { text: "Talk like a pirate until your next turn", type: "standard" },
    { text: "Use a deep voice until your next turn", type: "standard" },
    { text: "Use a high-pitched voice until your next turn", type: "standard" },
    { text: "Speak in slow motion until your next turn", type: "standard" },
    { text: "Talk really fast until your next turn", type: "standard" },
    { text: "Add 'like' to every sentence until your next turn", type: "standard" },
    { text: "End every sentence with 'and stuff' until next turn", type: "standard" },
    { text: "Speak only in questions until your next turn", type: "standard" },
    { text: "Talk like a news anchor until your next turn", type: "standard" },
    { text: "Speak like you're narrating a nature documentary", type: "standard" },
    { text: "Use movie quotes only until your next turn", type: "standard" },

    // Creative tasks - Mild
    { text: "G'day Mate! Speak in an Australian accent until your next turn", type: "standard" },
    { text: "Twitter! End each sentence with a hashtag until next turn. #DrunkJenga", type: "standard" },
    { text: "I Am Caveman! Only speak in 3-word sentences until next turn. 'Me like drink!'", type: "standard" },
    { text: "Hodor! You can only say 'Hodor' until your next turn. Hodor!", type: "standard" },
    { text: "Not Your Average Bible! End sentences like fake verses until next turn. 'I need water. Jenga 4:20'", type: "standard" },
    { text: "Nicknames! Give everyone at the table a corny nickname they must use", type: "standard" },
    { text: "Bipolar! Compliment the player to your right, then roast the player to your left", type: "standard" },
    { text: "Rock-Paper-Scissors! Challenge {other} - loser drinks 5 sips!", type: "standard" },
    { text: "Court Jester! Tell your best joke. Anyone who laughs drinks. No laughs? You drink 5!", type: "standard" },
    { text: "Rhyme Time! Pick a word, go clockwise rhyming. First to fail drinks 5!", type: "standard" },
    { text: "Category! Pick a category, go clockwise naming things. First to fail drinks 5!", type: "standard" },
    { text: "Great Lakes! Name the 5 Great Lakes. Drink 2 sips for each one you can't name!", type: "countdown", config: { duration: 15, task: "Name the 5 Great Lakes!" } },
    { text: "90's Music! Name three 90's bands. Drink 3 sips for each one you can't name!", type: "countdown", config: { duration: 10, task: "Name 3 bands from the 90s!" } },
    { text: "Actor Challenge! {other} names an actor - you must name 3 of their movies!", type: "countdown", config: { duration: 15, task: "Name 3 movies!" } },
    { text: "Pictionary! Draw an animal - others guess. If no one gets it, drink 5!", type: "countdown", config: { duration: 15, task: "Draw an animal!" } },
    { text: "Flip Cup! 3 attempts to flip a cup. Fail all 3? Finish your drink!", type: "standard" },
    { text: "Dentures! Cannot show your teeth until next turn. Each slip-up = 2 drinks!", type: "standard" },
    { text: "No Eye Contact! Drink each time you make eye contact until your next turn", type: "standard" },
    { text: "Cap Crown! Balance a bottle cap on your head. Drink every time it falls until next turn", type: "standard" }
  ],

  crazy: [
    // Intense drinking challenges with timers/spinners (25)
    { text: "Waterfall! You control when {all} stop drinking", type: "standard" },
    { text: "Viking! {all} must row - last one drinks 10 sips!", type: "timer", config: { duration: "5", showTime: false, sound: "buzzer", resultText: "Last one rowing drinks 10 sips!" } },
    { text: "Challenge {other} to rock-paper-scissors, loser drinks 8 sips", type: "standard" },
    { text: "Staring contest with {other} for 30 seconds, first to blink drinks 10", type: "countdown", config: { duration: 30, task: "Don't blink!" } },
    { text: "Thumb war with {other}, loser drinks 8 sips", type: "standard" },
    { text: "Pick your poison: 10 sips or 5 jumping jacks per sip", type: "standard" },
    { text: "Social! {all} drink 5 sips together", type: "standard" },
    { text: "Double social! {all} drink 8 sips", type: "standard" },
    { text: "Make a rule, anyone who breaks it drinks 5 sips", type: "standard" },
    { text: "Reverse! Person before you drinks 8 sips instead", type: "standard" },
    { text: "Drink every time someone says your name until next turn", type: "standard" },
    { text: "Hot seat: {all} ask you a question, drink per question", type: "standard" },
    { text: "Trivia: What year did the Titanic sink? Wrong = 10 sips", type: "standard" },
    { text: "Touch blue! Last one drinks 8 sips", type: "timer", config: { duration: "5", showTime: false, sound: "buzzer", resultText: "Last to touch blue drinks 8!" } },
    { text: "Stand up! Last one standing drinks 10 sips", type: "timer", config: { duration: "5", showTime: false, sound: "buzzer", resultText: "Slowest to stand drinks 10!" } },
    { text: "{other} tries to make you laugh for 15 seconds. Laugh = 8 sips!", type: "countdown", config: { duration: 15, task: "Don't laugh!" } },
    { text: "Hold your breath! Drink 2 sips per 5 seconds you lasted", type: "countdown", config: { duration: 30, task: "Hold your breath!" } },
    { text: "Drink for every person you've texted today (max 15)", type: "standard" },
    { text: "Drink for every app open on your phone (max 12)", type: "standard" },
    { text: "Spin to choose who drinks 10 sips!", type: "spinner", config: { resultText: "drinks 10 sips!" } },
    { text: "Mate: pick someone to drink every time you do", type: "standard" },
    { text: "Drink double whatever the next person has to drink", type: "standard" },
    { text: "Take a drink every time you blink for 30 seconds", type: "countdown", config: { duration: 30, task: "Drink when you blink!" } },
    { text: "Power hour: drink 5 sips now, 5 more on your next turn", type: "standard" },
    { text: "Guess odd/even on phone's last digit. Wrong = 10 sips", type: "standard" },

    // Hot potato / fuse timer tasks (10)
    { text: "Hot Potato! Pass the block around. When time's up, holder drinks 8!", type: "timer", config: { duration: "3+2n", showTime: false, sound: "explosion", resultText: "BOOM! Whoever has the block drinks 8 sips!" } },
    { text: "Bomb Pass! Pass this around - whoever has it when it explodes drinks 10!", type: "timer", config: { duration: "5+2n", showTime: false, sound: "explosion", resultText: "EXPLOSION! Block holder drinks 10 sips!" } },
    { text: "Musical Block! Keep passing until the music stops... holder drinks!", type: "timer", config: { duration: "4+2n", showTime: false, sound: "buzzer", resultText: "Music stopped! Holder drinks 8 sips!" } },
    { text: "Ticking Time Bomb! Pass it around, explosion = 12 sips for the holder!", type: "timer", config: { duration: "3+3n", showTime: false, sound: "explosion", resultText: "KABOOM! 12 sips for the unlucky holder!" } },
    { text: "Pass the Poison! When time runs out, whoever has it drinks 10!", type: "timer", config: { duration: "4+2n", showTime: false, sound: "explosion", resultText: "Poison activated! Holder drinks 10!" } },
    { text: "Hot Block Relay! Pass it fast! Slowpoke when it explodes drinks 15!", type: "timer", config: { duration: "2+2n", showTime: false, sound: "explosion", resultText: "TOO SLOW! Holder drinks 15 sips!" } },
    { text: "Grenade! Toss around until it blows - holder takes 10 sips!", type: "timer", config: { duration: "3+2n", showTime: false, sound: "explosion", resultText: "GRENADE! Holder drinks 10!" } },
    { text: "Time Bomb Challenge! Keep passing - loser drinks everyone's sips!", type: "timer", config: { duration: "4+2n", showTime: false, sound: "explosion", resultText: "BOOM! Holder drinks 2 sips per player!" } },
    { text: "Dynamite! Pass it around - fuse runs out, big drinks for the holder!", type: "timer", config: { duration: "3+2n", showTime: false, sound: "explosion", resultText: "DYNAMITE! Holder chugs for 5 seconds!" } },
    { text: "Nuclear Block! This one's dangerous - holder drinks 15 when it blows!", type: "timer", config: { duration: "5+2n", showTime: false, sound: "explosion", resultText: "MELTDOWN! Holder drinks 15 sips!" } },

    // Physical/endurance challenges (15)
    { text: "Stand on one foot until your next turn or drink constantly", type: "standard" },
    { text: "Keep your arms raised until your next turn or drink 8 sips", type: "standard" },
    { text: "Hold a squat position until your next turn", type: "standard" },
    { text: "Don't use your dominant hand until your next turn", type: "standard" },
    { text: "Close one eye until your next turn", type: "standard" },
    { text: "Keep your tongue out until your next turn", type: "standard" },
    { text: "Don't touch the table until your next turn", type: "standard" },
    { text: "Sit on the floor until your next turn", type: "standard" },
    { text: "Stand behind your chair until your next turn", type: "standard" },
    { text: "Balance the block on your head for 20 seconds, fall = 10 sips", type: "countdown", config: { duration: 20, task: "Balance the block!" } },
    { text: "Do a wall sit for 45 seconds or drink 10 sips", type: "countdown", config: { duration: 45, task: "WALL SIT! Don't give up!" } },
    { text: "Plank for 30 seconds or drink 8 sips", type: "countdown", config: { duration: 30, task: "PLANK! Hold strong!" } },
    { text: "Hold hands with both neighbors until your next turn", type: "standard" },
    { text: "Keep one hand on your head until your next turn", type: "standard" },
    { text: "Remain perfectly still for 30 seconds or drink 8 sips", type: "countdown", config: { duration: 30, task: "Freeze! Don't move!" } },

    // More physical challenges (10)
    { text: "Army crawl across the room and back", type: "standard" },
    { text: "Do 20 pushups while {all} count together", type: "countdown", config: { duration: 45, task: "20 pushups - {all} count!" } },
    { text: "Do 30 jumping jacks while {all} cheer", type: "countdown", config: { duration: 30, task: "30 jumping jacks!" } },
    { text: "Hold a pen between your nose and lip for 20 seconds", type: "countdown", config: { duration: 20, task: "Pen balance!" } },
    { text: "Walk around the table once on your knees", type: "standard" },
    { text: "Crab walk to the other side of the room", type: "standard" },
    { text: "Do 15 burpees or drink 15 sips", type: "countdown", config: { duration: 60, task: "15 burpees - GO!" } },
    { text: "Sprint in place for 30 seconds as fast as possible", type: "countdown", config: { duration: 30, task: "SPRINT! Faster!" } },
    { text: "Do 10 jump squats or drink 12 sips", type: "countdown", config: { duration: 30, task: "10 jump squats!" } },
    { text: "Don't let your back touch your chair until next turn", type: "standard" },

    // Role/character challenges (20)
    { text: "Speak in third person until your next turn", type: "standard" },
    { text: "Pretend to be {other} until your next turn", type: "standard" },
    { text: "Act like a celebrity until someone guesses who", type: "standard" },
    { text: "Be a mime until your next turn - no talking!", type: "standard" },
    { text: "Narrate everything you do until next turn", type: "standard" },
    { text: "Respond only with song lyrics until next turn", type: "standard" },
    { text: "Speak only in movie quotes until next turn", type: "standard" },
    { text: "Pretend you're royalty until your next turn", type: "standard" },
    { text: "Act scared of {other} until your next turn", type: "standard" },
    { text: "Pretend to be in love with {other} until next turn", type: "standard" },
    { text: "Be overly dramatic about everything until next turn", type: "standard" },
    { text: "Speak like Shakespeare until your next turn", type: "standard" },
    { text: "Pretend you don't understand English until next turn", type: "standard" },
    { text: "Act like a villain until your next turn", type: "standard" },
    { text: "Be a sports commentator until your next turn", type: "standard" },
    { text: "Pretend to be an alien learning human customs", type: "standard" },
    { text: "Act like a detective investigating the game", type: "standard" },
    { text: "Be a game show host until your next turn", type: "standard" },
    { text: "Pretend you're invisible until your next turn", type: "standard" },
    { text: "Act extremely old until your next turn", type: "standard" },

    // Voting tasks (10)
    { text: "Vote: Who is most likely to become famous? They drink 8!", type: "vote", config: { question: "Who is most likely to become famous?", resultText: "drinks 8 sips for future fame!" } },
    { text: "Vote: Who is most likely to get lost? They drink 8!", type: "vote", config: { question: "Who is most likely to get lost?", resultText: "drinks 8 sips for poor navigation!" } },
    { text: "Vote: Who is most likely to be late? They drink 8!", type: "vote", config: { question: "Who is most likely to be late?", resultText: "drinks 8 sips for tardiness!" } },
    { text: "Vote: Who is most likely to win the lottery and lose the ticket? 10 sips!", type: "vote", config: { question: "Who would lose a winning lottery ticket?", resultText: "drinks 10 sips for carelessness!" } },
    { text: "Vote: Who is the worst liar here? They drink 8!", type: "vote", config: { question: "Who is the worst liar?", resultText: "drinks 8 sips for honesty!" } },
    { text: "Vote: Who talks the most? They drink 10!", type: "vote", config: { question: "Who talks the most?", resultText: "drinks 10 sips for chattiness!" } },
    { text: "Vote: Who would survive longest in a zombie apocalypse? Others drink 5!", type: "vote", config: { question: "Who survives the zombie apocalypse?", resultText: "is safe - everyone else drinks 5!" } },
    { text: "Vote: Who is most likely to cry at a movie? They drink 8!", type: "vote", config: { question: "Who cries at movies?", resultText: "drinks 8 sips for being emotional!" } },
    { text: "Vote: Who has the best dance moves? They assign 10 sips!", type: "vote", config: { question: "Who has the best dance moves?", resultText: "assigns 10 sips to anyone!" } },
    { text: "Vote: Who is most likely to forget this night? They drink 10!", type: "vote", config: { question: "Who will forget tonight?", resultText: "drinks 10 sips preemptively!" } },

    // Spinner tasks (5)
    { text: "Spin to pick who does 10 pushups!", type: "spinner", config: { resultText: "does 10 pushups!" } },
    { text: "Spin to pick who tells an embarrassing story!", type: "spinner", config: { resultText: "tells their most embarrassing story!" } },
    { text: "Spin twice - those two must drink together!", type: "spinner", config: { resultText: "is drinking partner #1! Spin again for partner #2!" } },
    { text: "Spin to pick the next Question Master!", type: "spinner", config: { resultText: "is the new Question Master!" } },
    { text: "Spin to decide who gets to make a new rule!", type: "spinner", config: { resultText: "creates a new rule for the game!" } },

    // Group/social chaos (10)
    { text: "Swap seats with {other} for 3 rounds", type: "standard" },
    { text: "You and {other} become a team, share all drinks", type: "standard" },
    { text: "{all} must get {player}'s permission to drink", type: "standard" },
    { text: "Truth or dare {other}: they choose, you decide the task", type: "standard" },
    { text: "Story time: Start a story, each person adds a sentence, drink after", type: "standard" },
    { text: "Do your best impression of {other}, if they don't guess it's them, they drink 8", type: "standard" },
    { text: "Start a chant, {all} must join or drink 5 sips each", type: "standard" },
    { text: "Lead a toast speech about {other}, {all} drink after", type: "standard" },
    { text: "Dance battle with {other}! Spin to pick the judge!", type: "spinner", config: { resultText: "is the dance battle judge!" } },
    { text: "Arm wrestle {other}, loser drinks 8 sips", type: "standard" },

    // More group chaos (5)
    { text: "Stare into {other}'s eyes for 30 seconds. First to look away drinks 8", type: "countdown", config: { duration: 30, task: "Staring contest!" } },
    { text: "Confession time: Tell {other} something you've never told them", type: "standard" },
    { text: "Propose a lighthearted toast to {other}'s worst trait", type: "standard" },
    { text: "{all} close eyes. Assign 15 total sips however you want", type: "standard" },
    { text: "Play dead until someone checks on you. They drink 8 sips", type: "standard" },

    // Rule makers (15)
    { text: "New rule: No pointing! Violators drink 3 sips", type: "standard" },
    { text: "New rule: No saying 'drink'! Say 'hydrate' instead", type: "standard" },
    { text: "New rule: Must knock before drinking", type: "standard" },
    { text: "New rule: No first names! Use last names only", type: "standard" },
    { text: "New rule: Must say 'please' before picking up water", type: "standard" },
    { text: "New rule: No elbows on table!", type: "standard" },
    { text: "New rule: Must speak in questions for 3 rounds", type: "standard" },
    { text: "New rule: High-five before pulling a block", type: "standard" },
    { text: "New rule: Must compliment the previous player", type: "standard" },
    { text: "New rule: Alternate hands when drinking", type: "standard" },
    { text: "New rule: Must wink after every sip", type: "standard" },
    { text: "New rule: Can't say 'I' - use your name instead", type: "standard" },
    { text: "New rule: No laughing for 2 rounds!", type: "standard" },
    { text: "New rule: Pinky out when drinking", type: "standard" },
    { text: "New rule: Must clink glasses before drinking", type: "standard" },

    // Creative tasks - Crazy
    { text: "Shot Ski! Spin to pick 3 others to take drinks with you!", type: "spinner", config: { resultText: "joins the shot ski! Spin again for more!" } },
    { text: "Death! Take 4 big drinks. No mercy.", type: "standard" },
    { text: "Life! Hand out 4 drinks to anyone you choose!", type: "standard" },
    { text: "Ripple! Take 1 drink. Players on each side take 2. Next take 3. And so on!", type: "standard" },
    { text: "Dance! Solo dance for 60 seconds. The most feared block!", type: "countdown", config: { duration: 60, task: "DANCE! Show us your moves!" } },
    { text: "Twerk! Show us your best twerk attempt! Drink 5 after.", type: "standard" },
    { text: "Pokémon! Name as many Pokémon as you can. Hand out 1 drink per Pokémon!", type: "countdown", config: { duration: 15, task: "Name those Pokémon!" } },
    { text: "Big Cheese! Name types of cheese. Hand out 1 drink per cheese named!", type: "countdown", config: { duration: 15, task: "Name those cheeses!" } },
    { text: "Beer! Name beer brands. Hand out 1 drink per brand!", type: "countdown", config: { duration: 15, task: "Name those beer brands!" } },
    { text: "Tribal Council! Everyone votes - person with most votes finishes their drink!", type: "vote", config: { question: "Who gets voted off the island?", resultText: "has been voted out! Finish your drink!" } },
    { text: "Baby Got Back! Vote on who has the nicest booty - winner drinks 5!", type: "vote", config: { question: "Who has the best booty?", resultText: "has been blessed! Drink 5 sips!" } },
    { text: "Lyric Legend! Pick a song and sing along. Drink every time you mess up!", type: "countdown", config: { duration: 30, task: "Sing along without messing up!" } },
    { text: "Broken Toe! Stand on your tippy toes and draw another Jenga piece!", type: "standard" },
    { text: "T-Rex Arms! Tuck your arms in your shirt like a T-Rex and draw another piece!", type: "standard" },
    { text: "Rewind! Place this Jenga piece BACK into the tower. Good luck!", type: "standard" },
    { text: "At Your Service! You're the butler - must get/make all drinks for 5 minutes!", type: "countdown", config: { duration: 300, task: "Butler duty!" } },
    { text: "Flashback! Like an Instagram post that's at least 30 weeks old (not from anyone here)!", type: "standard" },
    { text: "Make a Rule! Create your own rule. Anyone who breaks it drinks 3!", type: "standard" },
    { text: "Influential Women! Name 5 influential women (not actresses/artists). Drink for each miss!", type: "countdown", config: { duration: 15, task: "Name 5 influential women!" } },
    { text: "I See London! Guess each player's underwear color. Drink for each wrong guess!", type: "standard" },
    { text: "Sex Noise! Make your best... impression. Then drink 3 for your troubles.", type: "standard" },
    { text: "Confessions! Share who, where, and what position for your biggest fantasy. Or drink 10.", type: "standard" },
    { text: "Dick Pic! Take a photo of the Jenga piece between your legs. {other} picks who receives it!", type: "standard" },
    { text: "Waterfall Classic! Start drinking, players follow clockwise. Can't stop until person before you stops!", type: "standard" },
    { text: "Staring Contest! Challenge {other} to a staring contest. Loser drinks 8!", type: "countdown", config: { duration: 30, task: "Stare! Don't blink!" } },

    // Personal/Offensive Questions (Close Friends Only!)
    { text: "Heartbreak Hotel! Drink for every time you've been broken up with. Minimum 2.", type: "standard" },
    { text: "Body Count! Drink for your number. Or lie and drink 10 if anyone calls BS.", type: "standard" },
    { text: "Walk of Shame! Drink for every one-night stand you've had. Minimum 1.", type: "standard" },
    { text: "Cheater Cheater! Have you ever cheated? Drink 5 if yes, drink 3 for thinking about it.", type: "standard" },
    { text: "Daddy Issues! Drink if you have unresolved parental issues. Let's be honest, drink anyway.", type: "standard" },
    { text: "Therapy Session! Name something you should see a therapist about, then drink 4.", type: "standard" },
    { text: "Biggest Regret! Share your biggest life regret. Others drink if they've done worse.", type: "standard" },
    { text: "Ex Files! Drink for every ex whose number is still in your phone.", type: "standard" },
    { text: "DM Slides! Show your most embarrassing sent DM or drink 10.", type: "standard" },
    { text: "Drunk Texts! Read aloud your most recent drunk text or drink 8.", type: "standard" },
    { text: "Crier! Drink if you've cried in the last week. Double if it was over something stupid.", type: "standard" },
    { text: "Stalker Mode! Drink for how many times you've stalked an ex's social media this month.", type: "standard" },
    { text: "Bad in Bed! {other} rates your bedroom skills 1-10. Drink the difference from 10.", type: "standard" },
    { text: "Toxic Trait! Confess your most toxic trait. {all} drink if they relate.", type: "standard" },
    { text: "Liar Liar! What's the biggest lie you've told a partner? Drink 5 after confessing.", type: "standard" },
    { text: "Gold Digger! Would you date someone ugly for money? Be honest. Drink 4 either way.", type: "standard" },
    { text: "Freaky Friday! What's the weirdest place you've hooked up? Share or drink 8.", type: "standard" },
    { text: "Friend Zone! Drink for every person at this table you've thought about romantically.", type: "standard" },
    { text: "Settle! Name someone at this table you'd settle for. They drink 5, you drink 3.", type: "standard" },
    { text: "Kill, Marry, F***! {other} gives you 3 people at the table. Answer honestly or drink 10.", type: "standard" },
    { text: "Worst Kiss! Describe your worst kiss. If anyone here was involved, they drink double.", type: "standard" },
    { text: "Secret Crush! Have you ever had a crush on someone at this table? Drink if yes, wink at them.", type: "standard" },
    { text: "Size Matters! What's your honest opinion? Share or drink 6 for being a coward.", type: "standard" },
    { text: "Catfish! Show your most deceiving photo vs reality. {all} drink for the audacity.", type: "standard" },
    { text: "Parent Disappointment! What would disappoint your parents most? Share then drink 4.", type: "standard" },
    { text: "Broke AF! What's the brokest thing you've ever done? Drink for every person who judges you.", type: "standard" },
    { text: "Red Flags! {other} names your biggest red flag. Drink if you agree.", type: "standard" },
    { text: "Faked It! Have you ever faked it? Drink 3 if yes. Drink 5 if you're lying about saying no.", type: "standard" },
    { text: "Petty! What's the pettiest thing you've done to an ex? Share then drink 5.", type: "standard" },
    { text: "Hot Take! Share your most controversial opinion about relationships. {all} who disagree drink.", type: "standard" },
    { text: "Simp Alert! Who at this table would you simp for? They assign you 8 drinks.", type: "standard" },
    { text: "Embarrassing Kink! Share something weird you're into or drink 10. No judgment... maybe.", type: "standard" },
    { text: "Worst Date! Describe your worst date ever. {all} drink out of sympathy.", type: "standard" },
    { text: "Two-Faced! Say something nice about {other}, then something mean. Both of you drink.", type: "standard" },
    { text: "Jealous Type? Rate your jealousy 1-10 honestly. Drink that number.", type: "standard" },
    { text: "Ghosted! Drink for every person you've ghosted. Minimum 2 because we know you have.", type: "standard" },
    { text: "Rebound! Have you ever been someone's rebound? Drink 4. Were you the rebounder? Drink 6.", type: "standard" },
    { text: "Cringe! What's something you did that still keeps you up at night? Share and drink 5.", type: "standard" },
    { text: "Trust Issues! On a scale of 1-10, how much do you trust {other}? They drink the inverse.", type: "standard" },
    { text: "Overshare! Tell us something nobody asked about your love life. Then drink 4.", type: "standard" }
  ]
};

const PENALTIES = {
  calm: [
    { text: "Finish your current drink completely", type: "standard" },
    { text: "Take 10 big sips of water", type: "standard" },
    { text: "Take 12 sips while {all} count together", type: "countdown", config: { duration: 20, task: "{all} count to 12!" } },
    { text: "Do a lap around the room while drinking", type: "standard" },
    { text: "Refill your drink and take 8 sips immediately", type: "standard" },
    { text: "Toast to your clumsiness and drink 10 sips", type: "standard" },
    { text: "Take a sip for every person playing", type: "standard" },
    { text: "Chug for 8 seconds straight", type: "countdown", config: { duration: 8, task: "CHUG!" } },
    { text: "Drink while doing 5 jumping jacks", type: "standard" },
    { text: "Drink while standing on one foot", type: "standard" },
    { text: "Take 15 small sips without stopping", type: "standard" },
    { text: "Drink while {all} sing Happy Birthday to you", type: "standard" },
    { text: "Down 10 sips with your non-dominant hand", type: "standard" },
    { text: "Drink while maintaining eye contact with {other}", type: "standard" },
    { text: "Take the 'walk of shame' around the table while drinking", type: "standard" }
  ],

  mild: [
    { text: "Finish your drink and immediately refill and drink half", type: "standard" },
    { text: "Take 15 sips while doing squats", type: "countdown", config: { duration: 30, task: "Squat and sip!" } },
    { text: "Drink for 15 seconds without stopping", type: "countdown", config: { duration: 15, task: "Keep drinking!" } },
    { text: "Do 20 pushups while {all} count, then drink 10 sips", type: "countdown", config: { duration: 45, task: "20 pushups then drink!" } },
    { text: "Do 25 jumping jacks, then chug for 10 seconds", type: "countdown", config: { duration: 40, task: "Jumping jacks, then chug!" } },
    { text: "Drink while everyone tells you what you did wrong", type: "standard" },
    { text: "Take 20 sips while spinning slowly", type: "standard" },
    { text: "Waterfall: drink until every other player has started and stopped", type: "standard" },
    { text: "Run a lap around the room, then drink 15 sips", type: "standard" },
    { text: "Do a wall sit while drinking your entire glass", type: "countdown", config: { duration: 30, task: "Wall sit while drinking!" } },
    { text: "Plank for 30 seconds, then drink 12 sips", type: "countdown", config: { duration: 30, task: "Plank then drink!" } },
    { text: "Drink 18 sips while hopping on one foot", type: "standard" },
    { text: "Hold the next block on your head while drinking 15 sips", type: "standard" },
    { text: "Do 15 burpees, then drink 10 sips", type: "countdown", config: { duration: 45, task: "15 burpees!" } },
    { text: "Balance on one foot for 45 seconds while drinking, fall = start over", type: "countdown", config: { duration: 45, task: "Balance and drink!" } }
  ],

  crazy: [
    { text: "Become the butler/servant for the next 5 minutes", type: "countdown", config: { duration: 300, task: "Butler duty!" } },
    { text: "Take 20 sips while the group roasts you", type: "standard" },
    { text: "Do 30 pushups, drink between each set of 10", type: "countdown", config: { duration: 90, task: "30 pushups with drink breaks!" } },
    { text: "Drink 25 sips while doing a wall sit", type: "countdown", config: { duration: 45, task: "Wall sit + 25 sips!" } },
    { text: "Chug an entire glass while {all} chant your name", type: "standard" },
    { text: "Run to another room and back, then drink 20 sips", type: "standard" },
    { text: "Do your best impression of everyone, drink 5 sips per person", type: "standard" },
    { text: "Wear something inside out for the rest of the game + drink 15 sips", type: "standard" },
    { text: "Let {all} pick your phone wallpaper + drink 15 sips", type: "standard" },
    { text: "Do 50 jumping jacks while {all} count", type: "countdown", config: { duration: 60, task: "50 jumping jacks!" } },
    { text: "Speak in a funny voice for the rest of the game + drink 20 sips", type: "standard" },
    { text: "Let {all} draw on your arm with washable marker + drink 15 sips", type: "standard" },
    { text: "Do an embarrassing dance for 30 seconds + drink 20 sips", type: "countdown", config: { duration: 30, task: "Dance! Dance! Dance!" } },
    { text: "Read aloud the last 3 texts you received + drink 15 sips", type: "standard" },
    { text: "Be the 'hype person' for the next 3 rounds + drink 20 sips", type: "standard" }
  ]
};

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TASKS, PENALTIES };
}
